version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/app
    overwrite : yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    
environment:
  variables:
    CREDENTIALS_FILE: "service_account.json"
hooks:
  AfterInstall:
    - location: scripts/stop.sh
      timeout: 60
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: ubuntu
