name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  
env:
  S3_BUCKET_NAME: moneymade-github-action-s3-bucket

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
      
    - name: Build with Gradle and print build result
      run: |
        cd server/The_10th_Finance
        chmod +x gradlew
        ./gradlew build -x test
      shell: bash    
      
    # 임의로 2
    - name: Check jar file
      run: ls server/The_10th_Finance/build/libs/
      shell: bash
      
    # appspec.yml, scripts(start.sh, stop.sh)디렉토리 복사
    - name: Copy appspec.yml to current directory
      run: |
          cp server/The_10th_Finance/appspec.yml .
          cp -r server/The_10th_Finance/scripts .
      shell: bash
    
    # 임의 3
    - name: Copy jar file to current directory
      run: cp server/The_10th_Finance/build/libs/*.jar .
      shell: bash

    # build한 후 프로젝트를 압축합니다.
    - name: Make zip file
      run: zip -r ./practice-deploy.zip .
      shell: bash
    
    # Access Key와 Secret Access Key를 통해 권한을 확인합니다.
    # 아래 코드에 Access Key와 Secret Key를 직접 작성하지 않습니다.
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }} # 등록한 Github Secret이 자동으로 불려옵니다.
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # 등록한 Github Secret이 자동으로 불려옵니다.
        aws-region: ap-northeast-2
    
    # 압축한 프로젝트를 S3로 전송합니다.
    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./practice-deploy.zip s3://moneymade-github-action-s3-bucket/practice-deploy.zip
   
   # CodeDeploy에게 배포 명령을 내립니다.
    - name: Code Deploy
      run: >
        aws deploy create-deployment --application-name moneymade_deploy
        --deployment-config-name CodeDeployDefault.AllAtOnce
        --deployment-group-name moneymade_deploy_group
        --s3-location bucket=moneymade-github-action-s3-bucket,bundleType=zip,key=practice-deploy.zip
