
spring:
  # H2 Setting Info (H2 Console에 접속하기 위한 설정정보 입력)
  jwt:
    key: CODESTARTES_STQREWR_EWREWR_EXTENDKEY  # 민감한 정보는 시스템 환경 변수에서 로드한다.
    access-token-expiration-minutes: 1
    refresh-token-expiration-minutes: 420
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://moneymade-db.c3r6azftukjh.ap-northeast-2.rds.amazonaws.com:3306/moneymade?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

mail:
  address:
    admin: admin@gmail.com

jwt:
  key: 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  # 민감한 정보는 시스템 환경 변수에서 로드한다.
  access-token-expiration-minutes: 1
  refresh-token-expiration-minutes: 420

chatgpt:
  api-key:

google:
  recaptcha:
    secret-key: 6LfdeKEmAAAAAE6DVb7hyb-hTiVTpGkNHv-pnd4k
    
logging:
  file:
    name: /var/log/myapp.log
