
spring:
  logging:
    level:
      org.springframework.batch: DEBUG
  jwt:
    key: CODESTARTES_STQREWR_EWREWR_EXTENDKEY  # 민감한 정보는 시스템 환경 변수에서 로드한다.
    access-token-expiration-minutes: 1
    refresh-token-expiration-minutes: 420
#  h2:
#    console:
#      enabled: true
#      settings:
#        web-allow-others: true
#      path: /h2-console
#  datasource:
#    initialization-mode: always
#    driver-class-name: org.h2.Driver  # Database를 H2로 사용하겠다.
#    url: jdbc:h2:~/test5  # H2 접속 정보
#    username: sa  # H2 접속 시 입력할 username 정보 (원하는 것으로 입력)
#    password:  # H2 접속 시 입력할 password 정보 (원하는 것으로 입력)
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/10thFiance?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
      username: admin
      password: 12341234
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 672c98f8ff452089ee65
            clientSecret: 2ecb19dd7515ef741b4d4f8dd20f37021579ea73
          google:
            clientId: 44491036859-cn9bl46j639d7ohnodddra1kjd9s0rva.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile

mail:
  address:
    admin: admin@gmail.com

jwt:
  key: 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  # 민감한 정보는 시스템 환경 변수에서 로드한다.
  access-token-expiration-minutes: 1
  refresh-token-expiration-minutes: 420

chatgpt:
  api-key:

google:
  recaptcha:
    secret-key: 6LfdeKEmAAAAAE6DVb7hyb-hTiVTpGkNHv-pnd4k

dialogflow:
  project-id: newagent-rukf
  credentials-file: "https://moneymade-github-action-s3-bucket.s3.ap-northeast-2.amazonaws.com/newagent-rukf-63c5448f7346.json"
  session-id: my-fixed-session-id
