
spring:
  mail:
    port: 587
    host: smtp.gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            required: true
            enable: true
          socket-factory:
            port: 465
            fallback: false
            class: javax.net.ssl.SSLSocketFactory
    username: taehwansw@gmail.com
    password: rlncordvjtubmoln
    debug: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://moneymade-db.c3r6azftukjh.ap-northeast-2.rds.amazonaws.com:3306/10thFiance?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: admin
    password: 12341234
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    generate-ddl: true
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 672c98f8ff452089ee65
            clientSecret: 2ecb19dd7515ef741b4d4f8dd20f37021579ea73
          google:
            clientId: 44491036859-cn9bl46j639d7ohnodddra1kjd9s0rva.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile

mail:
  address:
    admin: admin@gmail.com

jwt:
  key: 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  # 민감한 정보는 시스템 환경 변수에서 로드한다.
  access-token-expiration-minutes: 60
  refresh-token-expiration-minutes: 420

chatgpt:
  api-key:

google:
  recaptcha:
    secret-key: 6LdwszsnAAAAADaKOz3DRGlKq_VApk5sBu5L8azz


dialogflow:
  project-id: newagent-rukf
credentials-file: ${CREDENTIALS_FILE}
session-id: my-fixed-session-id
